name: CI
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        name: Unit Tests
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - name: Run Tests
              run: go test -v ./...
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - run: go build

    verify-go:
        runs-on: ubuntu-latest
        name: Verify Go Code Consistency
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - run: go install golang.org/x/tools/cmd/goimports@latest

            - name: Verify Go Formatting
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make format-go

    verify-templ:
        runs-on: ubuntu-latest
        name: Verify Templ Code Consistency
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - name: Verify Templ Formatting
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make format-templ

            - name: Verify Templ Generation
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make generate-templ

    verify-tailwind:
        runs-on: ubuntu-latest
        name: Verify Tailwind
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v4

            - name: Install Node Modules
              run: npm install

            - name: Verify Tailwind
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make tailwind
