name: CI
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        name: Unit Tests
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - name: Run Tests
              run: go test -v ./...
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            - run: go build
    verify-generated:
        runs-on: ubuntu-latest
        name: Verify Generated Code
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-go@v4
              with:
                  go-version: stable

            # Node is used to run tailwind
            - uses: actions/setup-node@v4

            - name: "Install Node Modules"
              run: npm install

            - name: Verify Generated Templates
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: go tool templ generate

            - name: Verify Go Formatting
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make format-go

            - name: Verify Template Formatting
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make format-templ

            - name: Verify Tailwind
              uses: ./.github/actions/verify_code_consistency
              with:
                  cmd: make tailwind
